# Generated by Django 4.2 on 2023-06-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0003_alter_categoriaproducto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoriaProd',
                'verbose_name_plural': 'categoriasProd',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subCategoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TiendaApp.subcategoriaproducto'),
            preserve_default=False,
        ),
    ]
