# Generated by Django 4.2 on 2023-06-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0005_alter_subcategoriaproducto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoriaproducto',
            name='categorias',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TiendaApp.categoriaproducto'),
            preserve_default=False,
        ),
    ]
