# Generated by Django 5.0.4 on 2024-05-07 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('extra1_label', models.CharField(max_length=32)),
                ('extra1_state', models.BooleanField(default=False)),
                ('extra2_label', models.CharField(max_length=32)),
                ('extra2_state', models.BooleanField(default=False)),
                ('extra3_label', models.CharField(max_length=32)),
                ('extra3_state', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
