# Generated by Django 5.0.3 on 2024-04-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0006_subcategoriaproducto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
